version: 2

sources:
  - name: account_usage
    database: SNOWFLAKE
    schema: account_usage

    tables:
      - name: warehouse_metering_history
        description: 'Snowflake warehouse usage tracking'

  - name: bizops
    database: ANALYTICS
    schema: bizops

    tables:
      - name: snowflake_contract_rates
        description: 'Snowflake contract rates'

  - name: information_schema
    database: 'RAW'
    schema: information_schema

    tables:
      - name: columns
        description: 'All columns in RAW Snowflake Warehouse.'
