version: 2

sources:
  - name: util
    database: ANALYTICS
    schema: util

    tables:
      - name: world_cities
        description: 'City information (Latitude/Longitude)'
      - name: stop_words
        description: List of all/most stop words in the english language.
      - name: public_domains
        description: List of all/most public web/email domains.
      - name: postal_code_mapping
      - name: dates