version: 2

models:
  - name: license_overview
    description: Overview of license information

  - name: licenses
    description: Contains the license data with feature configuration as an aggregated table from both raw.mattermost2.license and raw.licenses.licenses.
  
  - name: license_daily_details
    description: Contatins a daily snapshot of licenses to trend licenses and configurations over time.

  - name: enterprise_license_mapping

  - name: enterprise_license_fact

  - name: license_server_fact
    description: Contains a single row per server per license for every time a license has appeared in the server's telemetry.