version: 2

sources:
  - name: ga_channelgrouping_source_users_org
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_channelgrouping_source_users_org

    tables: 
      - name: report
        description: 'Users visiting Mattermost.org by Source and Channel Grouping'

  - name: ga_channelgrouping_source_users_com
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_channelgrouping_source_users_com

    tables: 
      - name: report
        description: 'Users visiting Mattermost.com by Source and Channel Grouping'

  - name: ga_developers_pages_visits
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_developers_pages_visits_sources

    tables: 
      - name: report
        description: 'Page visits to developers.mattermost.com'
  
  - name: ga_mattermost_com_pages_visits
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_mattermost_com_pages_visits

    tables: 
      - name: report
        description: 'Page visits to Mattermost.com'

  - name: ga_mattermost_handbook_pages_visits
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_mattermost_handbook_pages_visits

    tables: 
      - name: report
        description: 'Page visits to Mattermost Handbook'

  - name: ga_licensing_pages_visits
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_licensing_pages_visits

    tables: 
      - name: report
        description: 'Page visits to Licensing'

  - name: ga_docs_pages_visits_sources
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_docs_pages_visits_sources

    tables: 
      - name: report
        description: 'Page visits to Docs'