# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mattermost_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

quoting:
    database: true
    identifier: false
    schema: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  mattermost_analytics:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      # Ideally this would have been named staging. Unfortunately there's already a schema with that name.
      schema: dbt_staging
      # Staging layer contains views. Running on hourly mode should introduce manageable load.
      tags: ['staging', 'hourly']
    intermediate:
      +materialized: ephemeral
      tags: ['intermediate']
      data_eng:
        schema: int_data_eng
        tags: ['nightly']
      web_app:
        schema: int_web_app
        tags: ['nightly']
    marts:
      +materialized: table
      tags: ['marts']
      data_eng:
        schema: mart_data_eng
        tags: ['nightly']
      web_app:
        schema: mart_web_app
        tags: ['nightly']
      release:
        schema: mart_release
        tags: ['nightly']
      sales:
        schema: mart_sales
        tags: ['nightly']
        hightouch:
          # Hightouch syncs should be as close to real time as possible.
          tags: ['hourly']
    utilities:
      +materialized: table
      schema: utilities
      tags: [ 'utilities' ]

  dbt_project_evaluator:
    schema:
      mart_dbt_project_evaluator

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

  mattermost_analytics:
    +enabled: true
    salesforce:
      +schema: seed_salesforce
      country_codes:
        # Override column types
        +column_types:
          code: varchar(2)
          name: varchar(50)

tests:
  dbt_project_evaluator:
    # Set DBT project
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"

# Configuration variables
vars:
  dbt_project_evaluator:
    # Set test and doc coverage to 75% (default is 100%)
    documentation_coverage_target: 75
    test_coverage_target: 75
    staging_prefixes: ['stg_', 'base_']
    marts_prefixes: ['fct_', 'dim_', 'grp_']

    # Community Server ID
  community_server_id : 93mykbogbjfrbbdqphx3zhze5c

  # Salesforce variables
  in_product_trial_campaign_id: 7013p000001NkNoAAK