version: 2

sources:
  - name: support_portal
    database: 'RAW'
    schema: support_portal
    loader: Rudderstack
    description: Support portal events pushed via Rudderstack.
    tags:
      - rudderstack

    tables:
      - name: pages
        description: 'The Customer Support Web Portal Mattermost Web Property User-Level Page Views.'