version: 2

models:
  - name: server_daily_details
    description: Production server daily details table. Derived from events.security. Only includes production servers defined by TEDAS logic.
    columns:
      - name: server_id
        tests:
          - not_null

  - name: downloads
    description: Mattermost downloads
  
  - name: contributor_employee_map_data
    description: Location data on contributors and employees

  - name: github_contributors
    description: Statistics on GitHub contributors
  
  - name: nps_data
    description: NPS scores and feedback
  
  - name: nps_user_monthly_score
    description: User NPS score snapshot at a monthly level. Retrieves the User's latest NPS score submission on or before the record month.

  - name: server_fact
    description: Production server attributes including the server's first active date (telemetry-enabled), last active date (telemetry-enabled), the all-time max active users logged on the server, and the last date the server logged active users.

  - name: orgm_delete_audit
    description: Audit log of records we've deleted from the OrgM schema based on the OrgM Delete_History__c object.
  
  - name: server_daily_details_ext
    description: Contains daily snapshot of all server-related fields and dimensions from staging server details tables per server.

  - name: licenses
    description: Contains the license data with feature configuration as an aggregated table from both raw.mattermost2.license and raw.licenses.licenses.
  
  - name: license_daily_details
    description: Contatins a daily snapshot of licenses to trend licenses and configurations over time.
