version: 2

sources:
  - name: mattermost
    database: ANALYTICS
    schema: mattermost

    tables: 
      - name: github_repo_categorization
      
      - name: licenses

      - name: version_release_dates
        description: The server version and associated release date (i.e. GA date).

      - name: onprem_clearbit
        description: Enriched data for on prem servers. Enrichment done using clearbit data.

      - name: cloud_clearbit
        description: Enriched data for cloud servers. Enrichment done using clearbit data.