version: 2

sources:
  - name: mattermost
    database: ANALYTICS
    schema: mattermost

    tables: 
      - name: github_repo_categorization
      
      - name: licenses

      - name: version_release_dates
        description: The server version and associated release date (i.e. GA date).