version: 2

sources:
  - name: mattermost
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: mattermost

    tables: 
      - name: github_contributions
      - name: licenses

      - name: version_release_dates
        description: The server version and associated release date (i.e. GA date).