version: 2

sources:
  - name: sales
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: sales

    tables:
      - name: commit_segment
      - name: commit_ww
      - name: commit_rep