from airflow.providers.cncf.kubernetes.secret import Secret

# Namespace where secrets are set
SECRET_NAMESPACE = "airflow2"

# dbt Cloud
DBT_CLOUD_API_KEY = Secret("env", "DBT_CLOUD_API_KEY", SECRET_NAMESPACE, "DBT_CLOUD_API_KEY")
DBT_CLOUD_API_ACCOUNT_ID = Secret("env", "DBT_CLOUD_API_ACCOUNT_ID", SECRET_NAMESPACE, "DBT_CLOUD_API_ACCOUNT_ID")

# Snowflake Load
SNOWFLAKE_LOAD_DATABASE = Secret("env", "SNOWFLAKE_LOAD_DATABASE", SECRET_NAMESPACE, "SNOWFLAKE_LOAD_DATABASE")
SNOWFLAKE_LOAD_ROLE = Secret("env", "SNOWFLAKE_LOAD_ROLE", SECRET_NAMESPACE, "SNOWFLAKE_LOAD_ROLE")
SNOWFLAKE_LOAD_PASSWORD = Secret("env", "SNOWFLAKE_LOAD_PASSWORD", SECRET_NAMESPACE, "SNOWFLAKE_LOAD_PASSWORD")
SNOWFLAKE_LOAD_USER = Secret("env", "SNOWFLAKE_LOAD_USER", SECRET_NAMESPACE, "SNOWFLAKE_LOAD_USER")
SNOWFLAKE_LOAD_WAREHOUSE = Secret("env", "SNOWFLAKE_LOAD_WAREHOUSE", SECRET_NAMESPACE, "SNOWFLAKE_LOAD_WAREHOUSE")

# Snowflake Transform
SNOWFLAKE_TRANSFORM_ROLE = Secret("env", "SNOWFLAKE_TRANSFORM_ROLE", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_ROLE")
SNOWFLAKE_TRANSFORM_SCHEMA = Secret("env", "SNOWFLAKE_TRANSFORM_SCHEMA", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_SCHEMA")
SNOWFLAKE_TRANSFORM_USER = Secret("env", "SNOWFLAKE_TRANSFORM_USER", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_USER")
SNOWFLAKE_TRANSFORM_WAREHOUSE = Secret(
    "env", "SNOWFLAKE_TRANSFORM_WAREHOUSE", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_WAREHOUSE"
)
SNOWFLAKE_TRANSFORM_LARGE_WAREHOUSE = Secret(
    "env", "SNOWFLAKE_TRANSFORM_LARGE_WAREHOUSE", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_LARGE_WAREHOUSE"
)
SNOWFLAKE_TRANSFORM_DATABASE = Secret(
    "env", "SNOWFLAKE_TRANSFORM_DATABASE", SECRET_NAMESPACE, "SNOWFLAKE_TRANSFORM_DATABASE"
)
SNOWFLAKE_USER = Secret("env", "SNOWFLAKE_USER", SECRET_NAMESPACE, "SNOWFLAKE_USER")
SNOWFLAKE_ACCOUNT = Secret("env", "SNOWFLAKE_ACCOUNT", SECRET_NAMESPACE, "SNOWFLAKE_ACCOUNT")
SNOWFLAKE_PASSWORD = Secret("env", "SNOWFLAKE_PASSWORD", SECRET_NAMESPACE, "SNOWFLAKE_PASSWORD")

# MM
MATTERMOST_WEBHOOK_URL = Secret("env", "MATTERMOST_WEBHOOK_URL", SECRET_NAMESPACE, "MATTERMOST_WEBHOOK_URL")
NPS_WEBHOOK_URL = Secret("env", "NPS_WEBHOOK_URL", SECRET_NAMESPACE, "NPS_WEBHOOK_URL")
DOCS_FEEDBACK_WEBHOOK_URL = Secret("env", "DOCS_FEEDBACK_WEBHOOK_URL", SECRET_NAMESPACE, "DOCS_FEEDBACK_WEBHOOK_URL")

# Permission Bot
PERMISSION_BOT_USER = Secret("env", "PERMISSION_BOT_USER", SECRET_NAMESPACE, "SNOWFLAKE_PERMISSION_USER")
PERMISSION_BOT_PASSWORD = Secret("env", "PERMISSION_BOT_PASSWORD", SECRET_NAMESPACE, "SNOWFLAKE_PERMISSION_PASSWORD")
PERMISSION_BOT_ACCOUNT = Secret("env", "PERMISSION_BOT_ACCOUNT", SECRET_NAMESPACE, "SNOWFLAKE_ACCOUNT")
PERMISSION_BOT_DATABASE = Secret("env", "PERMISSION_BOT_DATABASE", SECRET_NAMESPACE, "SNOWFLAKE_PERMISSION_DATABASE")
PERMISSION_BOT_ROLE = Secret("env", "PERMISSION_BOT_ROLE", SECRET_NAMESPACE, "SNOWFLAKE_PERMISSION_ROLE")
PERMISSION_BOT_WAREHOUSE = Secret("env", "PERMISSION_BOT_WAREHOUSE", SECRET_NAMESPACE, "SNOWFLAKE_PERMISSION_WAREHOUSE")


# Diagnostic Locations
DIAGNOSTIC_LOCATION_ONE = Secret("env", "DIAGNOSTIC_LOCATION_ONE", SECRET_NAMESPACE, "DIAGNOSTIC_LOCATION_ONE")
DIAGNOSTIC_LOCATION_TWO = Secret("env", "DIAGNOSTIC_LOCATION_TWO", SECRET_NAMESPACE, "DIAGNOSTIC_LOCATION_TWO")
RELEASE_LOCATION = Secret("env", "RELEASE_LOCATION", SECRET_NAMESPACE, "RELEASE_LOCATION")

CLEARBIT_KEY = Secret("env", "CLEARBIT_KEY", SECRET_NAMESPACE, "CLEARBIT_KEY")

GITHUB_FINEGRAIN_TOKEN = Secret("env", "GITHUB_FINEGRAIN_TOKEN", SECRET_NAMESPACE, "GITHUB_FINEGRAIN_TOKEN")

# GeoLite2 secrets
GEO_ACCOUNT_ID = Secret("env", "GEO_ACCOUNT_ID", SECRET_NAMESPACE, "GEO_ACCOUNT_ID")
GEO_LICENSE_ID = Secret("env", "GEO_LICENSE_ID", SECRET_NAMESPACE, "GEO_LICENSE_ID")
