version: 2

models:
  - name: daily_website_traffic
    description: The daily website traffic to Mattermost web properties - integrations.mattermost.com, customers.mattermost.com, and www.mattermost.com.

  - name: daily_page_views
    description: Google Analytics page views

  - name: user_agent_registry
    description: Contains all user agents collected via server-side and user event telemetry.

  - name: mattermost_docs_feedback
    description: Contains the feedback responses to the Mattermost Documentation modal regarding user satisfaction with Mattermost Documentation.