version: 2

sources:
  - name: mattermost_nps
    database: 'RAW'
    schema: mattermost_nps
    loader: Segment
    description: |
      Product telemetry data for RC builds. Telemetry is added via Segment (see [source](https://app.segment.com/smarttotem/sources/mattermost_nps/settings/sql)).
    tags:
      - segment

    tables:
      - name: nps_score
        description: 'NPS score data'
      
      - name: nps_feedback
        description: 'NPS feedback data'

  - name: mm_plugin_prod
    database: 'RAW'
    schema: mm_plugin_prod

    tables: 
      - name: nps_nps_score
        description: 'NPS score data'
      
      - name: nps_nps_feedback
        description: 'NPS feedback data'