version: 2

models:
  - name: account_health_score
    description: Overview of Account Health Score
    columns:
      - name: account_sfid
        tests:
          - not_null
  - name: zendesk_ticket_details
    description: Zendesk Ticket Details
    columns:
      - name: ticket_id
        tests:
          - not_null
  - name: renewal_rate_by_renewal_opportunity