version: 2

sources:
  - name: targets
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: targets

    tables:
      - name: curr_fy_arr_by_mo
        description: 'Current Fiscal Year Targets for ARR by Month'

      - name: curr_fy_arr_new_by_mo
        description: 'Current Fiscal Year Targets for New ARR by Month'

      - name: curr_fy_arr_exp_by_mo
        description: 'Current Fiscal Year Targets for Expansion ARR by Month'

      - name: curr_fy_arr_churn_by_mo
        description: 'Current Fiscal Year Targets for Churn ARR by Month'

      - name: curr_fy_tedas_7day_by_mo
        description: 'Current Fiscal Year Targets for TEDAS 7 Day by Month'
