version: 2

sources:
  - name: targets
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: targets

    tables:
      - name: target_fact
        description: 'Target fact table'
      
      - name: arr_by_mo
        description: 'Current Fiscal Year Targets for ARR by Month'

      - name: arr_new_by_mo
        description: 'Current Fiscal Year Targets for New ARR by Month'

      - name: arr_exp_by_mo
        description: 'Current Fiscal Year Targets for Expansion ARR by Month'

      - name: arr_churn_by_mo
        description: 'Current Fiscal Year Targets for Churn ARR by Month'

      - name: bookings_by_mo
        description: 'Current Fiscal Year Targets for Bookings by Month'

      - name: bookings_new_by_mo
        description: 'Current Fiscal Year Targets for New Bookings by Month'

      - name: bookings_exp_by_mo
        description: 'Current Fiscal Year Targets for Expansion Bookings by Month'

      - name: bookings_new_and_exp_by_mo
        description: 'Current Fiscal Year Targets for New & Expansion Bookings by Month'

      - name: bookings_ren_by_qtr
        description: 'Current Fiscal Year Targets for Renewal Bookings by Quarter'
      
      - name: tedas_7day_by_mo
        description: 'Current Fiscal Year Targets for TEDAS 7 Day by Month'

      - name: downloads_by_mo
        description: 'Current Fiscal Year Targets for Downloads by Month'

      - name: bookings_new_and_exp_by_rep_by_mo
        description: 'Current Fiscal Year Targets for New & Expansion Bookings by Rep by Month'

      - name: bookings_new_and_exp_by_segment_by_mo
        description: 'Current Fiscal Year Targets for New & Expansion Bookings by Rep by Month'
