name: "mm_snowflake"
version: "1.0"

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: "snowflake"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# ======
# Run Hooks
# ======
on-run-start:
    - "{{ resume_warehouse(var('warehouse_name')) }}"

on-run-end:
    - "{{ suspend_warehouse(var('warehouse_name')) }}"


quoting:
    database: true
    identifier: false
    schema: false

models:
  vars:
    warehouse_name: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"

  mm_snowflake:
    bizops:
      nightly:
        tags: ["bizops", "nightly"]

    blp:
      tags: "blp"

    cs:
      tags: "cs"

    events:
      nightly:
        tags: ["events", "nightly"]

    finance:
      tags: "finance"

    ga:
      tags: "ga"
    
    mattermost:
      nightly:
        tags: "nightly"

    staging:
      server:
        tags: ["server", "nightly"]

    qa:
      tags: "qa"

seeds:
  enabled: true
  schema: targets
  quote_columns: False

  mm_snowflake:
    sys_vars:
      schema: util
    excludable_servers_seed:
      schema: staging
    world_cities:
      schema: util
    snowflake_contract_rates:
      schema: bizops
    contributor_map_data:
      schema: mattermost
    staff_github_usernames:
      schema: employee
    target_fact:
      schema: tva
    account_industry_mapping:
      schema: util
    version_release_dates:
      schema: mattermost
    financial_statements:
      schema: finance
    financial_model:
      schema: finance
    github_repo_categorization:
      schema: mattermost
    github_contributions_all:
      schema: staging


