name: "mm_snowflake"
version: "1.0"

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: "snowflake"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
    database: true
    identifier: false
    schema: false

models:
  mm_snowflake:
    tags: "nightly"

seeds:
  enabled: true
  schema: seed_data
  quote_columns: False

  mm_snowflake:
    sys_vars:
      schema: util
    excludable_servers:
      schema: mattermost
    world_cities:
      schema: util
    contributor_map_data:
      schema: staging
    github_contributions:
      schema: mattermost
    staff_github_usernames:
      schema: employee
    testing:
      schema: util