version: 2

sources:
  - name: staging
    database: ANALYTICS
    schema: staging

    tables: 
      - name: contributor_map_data
      - name: hist_license_mapping
      - name: github_contributions_all
      - name: activities_fill_out_form
      - name: clearbit_onprem_exceptions