version: 2

sources:
  - name: staging
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: staging

    tables: 
      - name: contributor_map_data
      - name: hist_license_mapping
      - name: github_contributions_all
    