version: 2

models:
  - name: opportunity_ext
    description: Additional fields at an Opportunity level that do not exist on Opportunity naitively.
  - name: opportunity_snapshot
    description: Daily snapshot of OrgM Opportunities.
  - name: opportunitylineitem_snapshot
    description: Daily snapshot of OrgM Opportunity Line Items.
  - name: account_ext
    description: Additional fields at an Account level that do not exist on Account naitively.
  - name: campaignmember_ext
    description: Additional fields at an Campaign Member level that do not exist on Campaign Member naitively.