version: 2

sources:
  - name: orgm
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: orgm
    loader: Stitch
    loaded_at_field: _sdc_batched_at
    
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
        warn_after: {count: 8, period: hour}
        error_after: {count: 24, period: hour}

    tables: 
      - name: account
        description: 'SFDC Account'

      - name: opportunity
        description: 'SFDC Opportunity'

      - name: opportunitylineitem
        description: 'SFDC Opportunity Line Item'
      
      - name: contact
        description: 'SFDC Contact'

      - name: delete_history__c
        description: 'History of deleted objects in SFDC'