version: 2

models:
  - name: trial_requests
    description: Trial Requests from blapi
  - name: addresses
    description: Contains all addresses (billing & shipping) provided by customers (from blapi).
  - name: contact_us_requests
    description: Contains contact us requests (from blapi).
  - name: credit_cards
    description: Contains all credit cards provided by customers (from blapi).
  - name: customers_blapi
    description: Contains all customers and their specific attributes (from blapi).
  - name: features
    description: Contains all features provided by various skus (from blapi).
  - name: invoices_blapi
    description: Contains all Mattermost Cloud customer invoices (from blapi). Includes additional forecasted invoice total to provide current month forecasts.
    columns:
      - name: id
        tests:
          - not_null
          - unique
  - name: payment_methods
    description: Contains all payment methods provided by Mattermost customers (from blapi).
  - name: payments
    description: Contains all payments received by Mattermost customers (from blapi).
  - name: purchase_fact
    description: Contains all self-serve customer purchase details (via the Customer Web Portal) for Mattermost's on-prem & cloud offerings (from blapi).
  - name: subscriptions_blapi
    description: Contains all Mattermost subscriptions purchased via the Customer Web Portal for Mattermost's on-prem & cloud offerings (from blapi).
  - name: usage_events
    description: Contains a snapshot of cloud customer usage each day, as well as captures registered user deltas as the customer expands and contracts. Supports cloud invoicings ability to identify the max users associated with cloud installations each day.
  
  