version: 2
models:
  - name: account_util_dates
    description: Util for calculating ARR at Account Level
    columns:
      - name: account_sfid
        tests:
          - not_null
  - name: account_daily_arr
    description: Daily ARR at the Account level
    columns:
      - name: account_sfid
        tests:
          - not_null
  - name: account_daily_arr_deltas
    description: Daily ARR deltas at the Account level
    columns:
      - name: account_sfid
        tests:
          - not_null
  - name: account_monthly_arr_deltas
    description: Monthly ARR deltas at the Account level
    columns:
      - name: account_sfid
        tests:
          - not_null
  - name: account_monthly_arr_deltas_by_type
    description: Monthly Account ARR Deltas by ARR type
    columns:
      - name: account_sfid
        tests:
          - not_null