version: 2

sources:
  - name: mattermost_rn_mobile_release_builds_v2
    database: 'RAW'
    schema: mattermost_rn_mobile_release_builds_v2
    description: |
      Product telemetry data for RC builds. Telemetry is added via Segment (see [source](https://app.segment.com/smarttotem/sources/mattermost_rn_mobile_release_builds_v2/settings/sql)).

    tables: 
      - name: event
        description: 'Contains the raw mobile user event data.'