version: 2

sources:
  - name: licenses
    database: 'RAW'
    schema: licenses
    loader: Snowflake Stage
    tags:
      - stage

    tables:
      - name: licenses
        description: 'License data'