version: 2

models:
  - name: security
    description: Security data from diagnostics log entries
  
  - name: events_registry
    description: Contains id, name, category, and description of all user events currently being logged by Telemetry-Enabled Mattermost servers.

  - name: user_events_by_date
    description: Contains event uuid, user id, user role, event name, event category, and count of events performed each day.

  - name: user_events_by_date_agg
    description: Contains an aggregated version of user_events by date w/ MAU and DAU-specific dimensions.