version: 2

models:
  - name: security
    description: Security data from diagnostics log entries
  
  - name: events_registry
    description: Contains id, name, category, and description of all user events currently being logged by Telemetry-Enabled Mattermost servers.

  - name: user_events_by_date
    description: Contains event uuid, user id, user role, event name, event category, and count of events performed each day.

  - name: user_events_by_date_agg
    description: Contains an aggregated version of user_events by date w/ MAU and DAU-specific dimensions.

  - name: server_events_by_date
    description: Contains an aggregated version of user_events_by_date at the server level.

  - name: mobile_events
    description: The union of all mobile event telemetry tables being sent by rudderstack. Format for incoming telemetry is 1 table per event. Needed to union all of them together to create an aggregated table containing all mobile events for user_events_by_date data model.

  - name: incident_response_events
    description: The union of all incident response event telemetry tables being sent by rudderstack. Format for incoming telemetry is 1 table per event. Needed to union all of them together to create an aggregated table containing all incident response events.