version: 2

models:
  - name: security
    description: Security data from diagnostics log entries
  
  - name: events_registry
    description: Contains id, name, category, and description of all user events currently being logged by Telemetry-Enabled Mattermost servers.

  - name: user_events_by_date_agg
    description: Contains an aggregated version of user_events by date w/ MAU and DAU-specific dimensions.

  - name: server_events_by_date
    description: Contains an aggregated version of user_events_by_date at the server level.

  - name: mobile_events
    description: The union of all mobile event telemetry tables being sent by rudderstack. Format for incoming telemetry is 1 table per event. Needed to union all of them together to create an aggregated table containing all mobile events for user_events_by_date data model.

  - name: incident_response_events
    description: The union of all incident response event telemetry tables being sent by rudderstack. Format for incoming telemetry is 1 table per event. Needed to union all of them together to create an aggregated table containing all incident response events.

  - name: portal_events
    description: The union of all portal events, including subscriptions purchased and stripe card errors. Format for incoming telemetry is 1 table per event. Needed to union all of them together to create an aggregated table containing all events for user_events_by_date data model.

  - name: rudder_webapp_events
    description: The union of all webapp events to union with mobile and portal for timestamp-level composite of all user events.

  - name: segment_webapp_events
    description: The union of all segment webapp events (omitting those captured by rudder i.e. servers on newer versions).
  
  - name: segment_mobile_events
    description: The union of all segment mobile events (omitting those captured by rudder i.e. server on newer versions).

  - name: user_events_telemetry
    description: The union of all webapp, mobile, and portal events sent via Rudderstack (server versions >= 5.19).

  - name: plugin_events
    description: The union of all plugin telemetry relations capturing plugin telemetry on the Mattermost platform.

  - name: cloud_pageview_events
    description: The specific pageview events instrumented to capture the cloud signup/onboarding workflows.

  - name: cloud_portal_pageview_events
    description: The specific pageview events to capture the cloud workspace creation onboarding flow w/in the customer portal.

  - name: feature_flag_telemetry
    description: Split.io feature flag data for A/B testing features.

  - name: focalboard_event_telemetry
    description: Contains the tracked user events performed within the focalboard GUI.
