{{config({
    "materialized": "incremental",
    "schema": "events",
    "tags":["nightly"],
    "snowflake_warehouse": "transform_l"
  })
}}
-- depends_on: {{ ref('portal_events') }}
-- depends_on:  {{ ref('mobile_events') }}
-- depends_on: {{ ref('rudder_webapp_events') }} 
-- depends_on: {{ ref('segment_webapp_events') }} 
-- depends_on:{{ ref('segment_mobile_events') }}
-- depends_on: {{ ref('cloud_pageview_events') }} 
-- depends_on:{{ ref('cloud_portal_pageview_events') }}

{% set rudder_relations = get_rudder_relations(schema=["events"], database='ANALYTICS', 
                          table_inclusions="'portal_events','mobile_events','rudder_webapp_events','segment_webapp_events',
                                            'segment_mobile_events', 'cloud_pageview_events', 'cloud_portal_pageview_events'") %}
{{ union_relations(relations = rudder_relations[0], tgt_relation = rudder_relations[1], exclude=["CHANNEL_IDS_0","CHANNELSIDS_0","CHANNELSIDS_1","CHANNELSIDS_49","CHANNELSIDS_48","CHANNEL_IDS_2","MMCSRF"
"CHANNEL_IDS_0","CHANNEL_IDS_1","CHANNELSIDS_32","CHANNELSIDS_7","CHANNELSIDS_45","CHANNELSIDS_44","CHANNELSIDS_14","CHANNELSIDS_16","CHANNELSIDS_13","CHANNELSIDS_29","CHANNELSIDS_46","CHANNELSIDS_2",
"CHANNELSIDS_21","CHANNELSIDS_3","CHANNELSIDS_10","CHANNELSIDS_6","CHANNELSIDS_27","CHANNELSIDS_39","CHANNELSIDS_34","CHANNELSIDS_31","CHANNELSIDS_36","CHANNELSIDS_28","CHANNELSIDS_4","CHANNELSIDS_30",
"CHANNELSIDS_11","CHANNELSIDS_23","CHANNELSIDS_41","CHANNELSIDS_37","CHANNELSIDS_19","CHANNELSIDS_9","CHANNELSIDS_47","CHANNELSIDS_12","CHANNELSIDS_15","CHANNELSIDS_20","CHANNELSIDS_35","CHANNELSIDS_24","CHANNELSIDS_40",
"CHANNELSIDS_5","CHANNELSIDS_22","CHANNELSIDS_8","CHANNELSIDS_33","CHANNELSIDS_42","CHANNELSIDS_43","CHANNELSIDS_25","CHANNELSIDS_26","CHANNELSIDS_38","CHANNELSIDS_18","CHANNELSIDS_17","CONTEXT_TRAITS_41","CONTEXT_TRAITS_2",
"CONTEXT_TRAITS_9","CONTEXT_TRAITS_28","CONTEXT_TRAITS_53","CONTEXT_TRAITS_20","CONTEXT_TRAITS_40","CONTEXT_TRAITS_3","CONTEXT_TRAITS_1","CONTEXT_TRAITS_44","CONTEXT_TRAITS_10","CONTEXT_TRAITS_17","CONTEXT_TRAITS_34",
"CONTEXT_TRAITS_54","CONTEXT_TRAITS_15","CONTEXT_TRAITS_14","CONTEXT_TRAITS_31","CONTEXT_TRAITS_32","CONTEXT_TRAITS_38","CONTEXT_TRAITS_16","CONTEXT_TRAITS_56","CONTEXT_TRAITS_13","CONTEXT_TRAITS_23","CONTEXT_TRAITS_30",
"CONTEXT_TRAITS_39","CONTEXT_TRAITS_51","CONTEXT_TRAITS_45","CONTEXT_TRAITS_24","CONTEXT_TRAITS_47","CONTEXT_TRAITS_29","CONTEXT_TRAITS_19","CONTEXT_TRAITS_33","CONTEXT_TRAITS_55","CONTEXT_TRAITS_22","CONTEXT_TRAITS_11",
"CONTEXT_TRAITS_4","CONTEXT_TRAITS_27","CONTEXT_TRAITS_50","CONTEXT_TRAITS_12","CONTEXT_TRAITS_35","CONTEXT_TRAITS_37","CONTEXT_TRAITS_5","CONTEXT_TRAITS_21","CONTEXT_TRAITS_26","CONTEXT_TRAITS_6","CONTEXT_TRAITS_36",
"CONTEXT_TRAITS_57","CONTEXT_TRAITS_0","CONTEXT_TRAITS_42","CONTEXT_TRAITS_46","CONTEXT_TRAITS_52","CONTEXT_TRAITS_25","CONTEXT_TRAITS_43","CONTEXT_TRAITS_48","CONTEXT_TRAITS_7","CONTEXT_TRAITS_18","CONTEXT_TRAITS_8",
"CONTEXT_TRAITS_49","CONTEXT_TRAITS_123","CONTEXT_TRAITS_151","CONTEXT_TRAITS_164","CONTEXT_TRAITS_162","CONTEXT_TRAITS_147","CONTEXT_TRAITS_152","CONTEXT_TRAITS_157","CONTEXT_TRAITS_142","CONTEXT_TRAITS_165",
"CONTEXT_TRAITS_159","CONTEXT_TRAITS_156","CONTEXT_TRAITS_155","CONTEXT_TRAITS_153","CONTEXT_TRAITS_143","CONTEXT_TRAITS_163","CONTEXT_TRAITS_150","CONTEXT_TRAITS_144","CONTEXT_TRAITS_149","CONTEXT_TRAITS_160",
"CONTEXT_TRAITS_161","CONTEXT_TRAITS_158","CONTEXT_TRAITS_148","CONTEXT_TRAITS_146","CONTEXT_TRAITS_145","CONTEXT_TRAITS_154","CONTEXT_TRAITS_124","CONTEXT_TRAITS_129","CONTEXT_TRAITS_126","CONTEXT_TRAITS_134","CONTEXT_TRAITS_136","CONTEXT_TRAITS_140","CONTEXT_TRAITS_131","CONTEXT_TRAITS_132","CONTEXT_TRAITS_139","CONTEXT_TRAITS_133","CONTEXT_TRAITS_130","CONTEXT_TRAITS_141","CONTEXT_TRAITS_137","CONTEXT_TRAITS_135","CONTEXT_TRAITS_138",
"CONTEXT_TRAITS_125","CONTEXT_TRAITS_128","CONTEXT_TRAITS_122","CONTEXT_TRAITS_127","CONTEXT_TRAITS_117","CONTEXT_TRAITS_99","CONTEXT_TRAITS_86","CONTEXT_TRAITS_72","CONTEXT_TRAITS_92","CONTEXT_TRAITS_111","CONTEXT_TRAITS_85",
"CONTEXT_TRAITS_77","CONTEXT_TRAITS_105","CONTEXT_TRAITS_65","CONTEXT_TRAITS_64","CONTEXT_TRAITS_87","CONTEXT_TRAITS_82","CONTEXT_TRAITS_90","CONTEXT_TRAITS_101","CONTEXT_TRAITS_66","CONTEXT_TRAITS_106","CONTEXT_TRAITS_63",
"CONTEXT_TRAITS_80","CONTEXT_TRAITS_94","CONTEXT_TRAITS_110","CONTEXT_TRAITS_84","CONTEXT_TRAITS_96","CONTEXT_TRAITS_69","CONTEXT_TRAITS_78","CONTEXT_TRAITS_116","CONTEXT_TRAITS_73","CONTEXT_TRAITS_62","CONTEXT_TRAITS_75",
"CONTEXT_TRAITS_68","CONTEXT_TRAITS_60","CONTEXT_TRAITS_115","CONTEXT_TRAITS_81","CONTEXT_TRAITS_74","CONTEXT_TRAITS_59","CONTEXT_TRAITS_109","CONTEXT_TRAITS_67","CONTEXT_TRAITS_118","CONTEXT_TRAITS_93","CONTEXT_TRAITS_103",
"CONTEXT_TRAITS_58","CONTEXT_TRAITS_61","CONTEXT_TRAITS_95","CONTEXT_TRAITS_88","CONTEXT_TRAITS_119","CONTEXT_TRAITS_120","CONTEXT_TRAITS_113","CONTEXT_TRAITS_98","CONTEXT_TRAITS_107","CONTEXT_TRAITS_83","CONTEXT_TRAITS_71","CONTEXT_TRAITS_91","CONTEXT_TRAITS_121","CONTEXT_TRAITS_79","CONTEXT_TRAITS_108","CONTEXT_TRAITS_104", 
"CONTEXT_TRAITS_114","CONTEXT_TRAITS_112","CONTEXT_TRAITS_97","CONTEXT_TRAITS_100","CONTEXT_TRAITS_102",
"CONTEXT_TRAITS_89","CONTEXT_TRAITS_76","CONTEXT_TRAITS_70","T","D",
"CONTEXT_APP_PROTO_NODE_OPTIONS", "CONTEXT_CAMPAIGN_PROTO_SHELL", "CONTEXT_SCREEN_PROTO_SHELL", "CONTEXT_SCREEN_PROTO_ARGV_0", 
"CONTEXT_LIBRARY_PROTO_ENV_A_51_B_834_B_7", "CONTEXT_TRAITS_PROTO_ARGV_0", "__PROTO_ARGV_0", "CONTEXT_PAGE_PROTO_ENV_A_51_B_834_B_7", 
"CONTEXT_LIBRARY_PROTO_NODE_OPTIONS", "CONTEXT_OS_PROTO_SHELL", "__PROTO_SHELL", "CONTEXT_LIBRARY_PROTO_ARGV_0", "CONTEXT_OS_PROTO_NODE_OPTIONS", 
"CONTEXT_CAMPAIGN_PROTO_NODE_OPTIONS", "CONTEXT_OS_PROTO_ARGV_0", "CONTEXT_PAGE_PROTO_NODE_OPTIONS", "CONTEXT_CAMPAIGN_PROTO_ENV_A_51_B_834_B_7", 
"CONTEXT_PROTO_SHELL", "CONTEXT_TRAITS_PROTO_ENV_A_51_B_834_B_7", "CONTEXT_TRAITS_PROTO_SHELL", "CONTEXT_SCREEN_PROTO_ENV_A_51_B_834_B_7", 
"CONTEXT_LIBRARY_PROTO_SHELL", "__PROTO_ENV_A_51_B_834_B_7", "CONTEXT_OS_PROTO_ENV_A_51_B_834_B_7", "CONTEXT_PROTO_NODE_OPTIONS", 
"CONTEXT_PAGE_PROTO_ARGV_0", "CONTEXT_PAGE_PROTO_SHELL", "CONTEXT_CAMPAIGN_PROTO_ARGV_0", "CONTEXT_APP_PROTO_ARGV_0", 
"CONTEXT_APP_PROTO_ENV_A_51_B_834_B_7", "CONTEXT_PROTO_ENV_A_51_B_834_B_7", "CONTEXT_PROTO_ARGV_0", "CONTEXT_TRAITS_PROTO_NODE_OPTIONS", 
"CONTEXT_SCREEN_PROTO_NODE_OPTIONS", "__PROTO_NODE_OPTIONS", "CONTEXT_APP_PROTO_SHELL", "CONTEXT_TRAITS_167", "CONTEXT_TRAITS_176", 
"CONTEXT_TRAITS_166", "CONTEXT_TRAITS_173", "CONTEXT_TRAITS_177", "CONTEXT_TRAITS_180", "CONTEXT_TRAITS_184", "CONTEXT_TRAITS_174", 
"CONTEXT_TRAITS_185", "CONTEXT_TRAITS_172", "CONTEXT_TRAITS_175", "CONTEXT_TRAITS_182", "CONTEXT_TRAITS_170", "CONTEXT_TRAITS_179", 
"CONTEXT_TRAITS_183", "CONTEXT_TRAITS_181", "CONTEXT_TRAITS_168", "CONTEXT_TRAITS_178", "CONTEXT_TRAITS_169", "CONTEXT_TRAITS_171",
"CATGGORY","MMAUTHTOKEN","MMCSRF","NUM_HIGH","CONTEXT_APP_NAMGSPACE","CONTEXT_APP_WHERE","CONTEXT_CAMPAIGN","CONTEXT_CAMPAIGN_EXPID",
"CONTEXT_CAMPAIGN_ID","CONTEXT_CAMPAIGN_REFERRER","CONTEXT_CAMPAIGN_SOURCE_UTM_CAMPAIGN","CONTEXT_CAMPAIGN_SOURCES","CONTEXT_CAMPAIGN_WHERE",
"_WHERE","CONTEXT_LIBRARY_WHERE","CONTEXT_OS_WHERE","CONTEXT_PAGE_123","CONTEXT_PAGE_12551251","CONTEXT_PAGE_WHERE","CONTEXT_PASSED_IP",
"CONTEXT_REQUEST_IP","CONTEXT_SCREEN_INNER_HEIGHT","CONTEXT_SCREEN_INNER_WIDTH","CONTEXT_SCREEN_WHERE","CONTEXT_SCREGN_DENSITY","CONTEXT_SESSION_ID",
"CONTEXT_SESSION_START","CONTEXT_SOURCE_ID","CONTEXT_TRAITS_12551251","CONTEXT_TRAITS_ACTIVE_ADDRESS_ID","CONTEXT_TRAITS_ADDRESS","CONTEXT_TRAITS_BITS_PER_BLOCK",
"CONTEXT_TRAITS_BLACK_BLOCK","CONTEXT_TRAITS_CAP_HEIGHT","CONTEXT_TRAITS_CELLPHONE","CONTEXT_TRAITS_CITY","CONTEXT_TRAITS_COMPRESSION_TYPE",
"CONTEXT_TRAITS_CONTENT_TYPE","CONTEXT_TRAITS_DATE","CONTEXT_TRAITS_DEVICE_IS_TABLET","CONTEXT_TRAITS_DISTRICT","CONTEXT_TRAITS_EVENT_TENANT",
"CONTEXT_TRAITS_FIRSTNAME","CONTEXT_TRAITS_HORIZONTAL_SUBSAMPLING","CONTEXT_TRAITS_INSTALLATION_ID","CONTEXT_TRAITS_INSTANCE_ID","CONTEXT_TRAITS_ITEM_IN_CART",
"CONTEXT_TRAITS_LAST_AUDIENCE_VISIT","CONTEXT_TRAITS_LASTNAME","CONTEXT_TRAITS_LATITUDE","CONTEXT_TRAITS_LEADING_OVERRIDE","CONTEXT_TRAITS_LONGITUDE",
"CONTEXT_TRAITS_NAME","CONTEXT_TRAITS_NB_OF_AUDIENCE_VISIT","CONTEXT_TRAITS_NSCT_FONT_UI_USAGE_ATTRIBUTE","CONTEXT_TRAITS_OPTICAL_SIZE","CONTEXT_TRAITS_ORDER_ID",
"CONTEXT_TRAITS_PROVINCE","CONTEXT_TRAITS_REFERRER","CONTEXT_TRAITS_SESSION_ID","CONTEXT_TRAITS_SHIPPING_METHOD_KIND","CONTEXT_TRAITS_SIZE_CATEGORY",
"CONTEXT_TRAITS_SUBDISTRICT","CONTEXT_TRAITS_TENANT","CONTEXT_TRAITS_TILE_HEIGHT","CONTEXT_TRAITS_TILE_WIDTH","CONTEXT_TRAITS_TILED_ADDRESS_FORMAT",
"CONTEXT_TRAITS_VERSION_CLI","CONTEXT_TRAITS_VERTICAL_SUBSAMPLING","CONTEXT_TRAITS_VIA","CONTEXT_TRAITS_WHERE","CONTEXT_TRAITS_X_AMZ_CF_POP",
"CONTEXT_TRAITS_X_CACHE", "_"]) }}
