name: Aiflow Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-airflow.yml'
      - 'airflow/**'
      - 'build/requirements-airflow-dev.txt'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ci-airflow.yml'
      - 'airflow/**'
      - 'build/requirements-airflow-dev.txt'

jobs:
  tests:
    name: Testing Plugins and DAGs
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'   # This is the python version in the airflow docker image currently used
          cache: 'pip'               # caching pip dependencies
          cache-dependency-path: 'build/requirements-airflow-dev.txt'

      - name: Install dependencies
        working-directory: ./airflow
        run: poetry install

      - name: Run tests
        working-directory: ./airflow
        run: poetry run pytest --cov
