name: Permifrost Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-permifrost.yml'
      - 'build/permifrost.Dockerfile'
      - 'build/.yamllint.yml'
      - 'load/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ci-permifrost.yml'
      - 'build/permifrost.Dockerfile'
      - 'build/.yamllint.yml'
      - 'load/**'

jobs:
  tests:
    name: Lint YAML file
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # v.3.3.0
        with:
          fetch-depth: 1

      - name: Lint YAML file
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  #v3.1.1
        with:
          file_or_dir: load/snowflake/roles.yaml
          config_file: build/.yamllint.yml
          format: github

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # v.3.3.0
        with:
          fetch-depth: 1

      - name: Lint docker image
        run: make permifrost-docker-lint

      - name: Build & push docker image
        run: make docker-login && make permifrost-docker-build && make permifrost-docker-push
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sign docker image
        run: make permifrost-docker-sign && make permifrost-docker-verify
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
