version: 2

models:
  
  - name: tva_arr_by_mo
    description: ARR by Month Target vs Actuals for the Current Fiscal Year
  
  - name: tva_arr_new_by_mo
    description: New ARR by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_arr_exp_by_mo
    description: Expansion ARR by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_arr_churn_by_mo
    description: Churn ARR by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_by_mo
    description: Bookings by Month Target vs Actuals for the Current Fiscal Year  
  
  - name: tva_bookings_new_by_mo
    description: New Booking by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_exp_by_mo
    description: Expansion Bookings by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_ren_by_mo
    description: Renewal Bookings by Month Target vs Actuals for the Current Fiscal Year

  - name: tva_tedas_7day_by_mo
    description: TEDAS > 7 Day by Month Target vs Actuals for the Current Fiscal Year
  
  - name: tva_arr_by_qtr
    description: ARR by Quarter Target vs Actuals for the Current Fiscal Year
  
  - name: tva_arr_new_by_qtr
    description: New ARR by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_arr_exp_by_qtr
    description: Expansion ARR by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_arr_churn_by_qtr
    description: Churn ARR by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_by_qtr
    description: Bookings by Quarter Target vs Actuals for the Current Fiscal Year  
  
  - name: tva_bookings_new_by_qtr
    description: New Booking by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_exp_by_qtr
    description: Expansion Bookings by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_bookings_ren_by_qtr
    description: Renewal Bookings by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_tedas_7day_by_qtr
    description: TEDAS > 7 Day by Quarter Target vs Actuals for the Current Fiscal Year
  
  - name: tva_downloads_by_mo
    description: Downloads by Day Target vs Actuals for the Current Fiscal Year

  - name: tva_downloads_by_qtr
    description: Downloads by Quarter Target vs Actuals for the Current Fiscal Year

  - name: tva_downloads_by_fy
    description: Downloads by Fiscal Year Target vs Actuals for the Current Fiscal Year
  